-- Sentinel schema (Cloudflare D1 / SQLite)
--
-- Ported from the original Postgres schema. Notable differences from a
-- Postgres schema, since D1 is SQLite under the hood:
--   * No UUID type / gen_random_uuid() -> ids are TEXT, generated by the
--     Worker with crypto.randomUUID() at insert time (not by the DB).
--   * No ENUM type -> TEXT + CHECK constraint.
--   * No JSONB -> TEXT holding a JSON string, parsed/stringified in the Worker.
--   * No TIMESTAMPTZ -> TEXT holding a full ISO-8601 UTC string
--     (e.g. "2026-08-07T12:34:56.789Z"), always written by the Worker via
--     `new Date().toISOString()` so it sorts and compares correctly as text.
--   * Partial unique indexes (WHERE ...) are supported by SQLite, so the
--     dedupe-by-external-id behavior carries over unchanged.

CREATE TABLE sources (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL CHECK (type IN ('social', 'news', 'darkweb', 'forum')),
    enabled INTEGER NOT NULL DEFAULT 1,
    -- Connector config lives here (API keys are referenced by env var name, never stored in plaintext).
    config TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
);

CREATE TABLE events (
    id TEXT PRIMARY KEY,
    source_id TEXT REFERENCES sources(id) ON DELETE SET NULL,
    source_type TEXT NOT NULL CHECK (source_type IN ('social', 'news', 'darkweb', 'forum')),
    external_id TEXT,
    author TEXT,
    content TEXT NOT NULL,
    url TEXT,
    lang TEXT DEFAULT 'en',
    sentiment REAL, -- -1 (negative) to 1 (positive)
    published_at TEXT NOT NULL,
    ingested_at TEXT NOT NULL,
    geo_lat REAL,
    geo_lng REAL,
    geo_label TEXT,
    raw_metadata TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX idx_events_published_at ON events (published_at DESC);
CREATE INDEX idx_events_source_type ON events (source_type);

-- Lets real connectors (GDELT, RSS, etc) dedupe-insert using their native
-- article/post ID, without affecting mock events (external_id NULL).
CREATE UNIQUE INDEX idx_events_external_id_unique ON events (source_type, external_id) WHERE external_id IS NOT NULL;

CREATE TABLE users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('admin', 'client')),
    created_at TEXT NOT NULL
);

CREATE TABLE monitoring_queries (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    boolean_query TEXT NOT NULL, -- e.g. ("cholera" OR "outbreak") AND "Nairobi" NOT "drill"
    category TEXT DEFAULT 'general', -- public_health, civil_unrest, natural_disaster, cyber, etc.
    is_active INTEGER NOT NULL DEFAULT 1,
    baseline_window_minutes INTEGER NOT NULL DEFAULT 60,
    elevated_threshold REAL NOT NULL DEFAULT 2.5, -- z-score-ish trigger
    critical_threshold REAL NOT NULL DEFAULT 4.0,
    -- NULL = "house" query not owned by any client, visible only to admins.
    owner_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_monitoring_queries_owner ON monitoring_queries (owner_id);

CREATE TABLE query_matches (
    id TEXT PRIMARY KEY,
    query_id TEXT NOT NULL REFERENCES monitoring_queries(id) ON DELETE CASCADE,
    event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    matched_at TEXT NOT NULL,
    UNIQUE (query_id, event_id)
);

CREATE INDEX idx_query_matches_query_time ON query_matches (query_id, matched_at DESC);

CREATE TABLE alerts (
    id TEXT PRIMARY KEY,
    query_id TEXT REFERENCES monitoring_queries(id) ON DELETE CASCADE,
    level TEXT NOT NULL CHECK (level IN ('info', 'elevated', 'critical')),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    metric_snapshot TEXT NOT NULL DEFAULT '{}',
    geo_label TEXT,
    geo_lat REAL,
    geo_lng REAL,
    created_at TEXT NOT NULL,
    acknowledged_at TEXT,
    resolved_at TEXT
);

CREATE INDEX idx_alerts_created_at ON alerts (created_at DESC);
CREATE INDEX idx_alerts_level ON alerts (level);

CREATE TABLE escalation_snapshots (
    id TEXT PRIMARY KEY,
    query_id TEXT NOT NULL REFERENCES monitoring_queries(id) ON DELETE CASCADE,
    window_start TEXT NOT NULL,
    window_end TEXT NOT NULL,
    volume INTEGER NOT NULL,
    baseline_volume REAL NOT NULL,
    avg_sentiment REAL,
    escalation_score REAL NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX idx_escalation_query_time ON escalation_snapshots (query_id, window_end DESC);

-- Seed a handful of default sources and starter monitoring queries.
-- Ids are generated with SQLite's randomblob() since this runs once via
-- `wrangler d1 execute`, outside the Worker (which normally mints ids with
-- crypto.randomUUID()).
INSERT INTO sources (id, name, type, created_at) VALUES
    (lower(hex(randomblob(16))), 'Simulated Social Firehose', 'social', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    (lower(hex(randomblob(16))), 'Simulated News Wire', 'news', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    (lower(hex(randomblob(16))), 'Simulated Forum Chatter', 'forum', strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    (lower(hex(randomblob(16))), 'Simulated Dark Web Feed', 'darkweb', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));

INSERT INTO monitoring_queries (id, name, boolean_query, category, created_at, updated_at) VALUES
    (lower(hex(randomblob(16))), 'Disease Outbreak Chatter', '("outbreak" OR "cholera" OR "measles" OR "hemorrhagic fever") AND ("hospital" OR "cases" OR "quarantine")', 'public_health', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    (lower(hex(randomblob(16))), 'Civil Unrest Signals', '("protest" OR "riot" OR "unrest" OR "curfew") AND NOT "drill"', 'civil_unrest', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    (lower(hex(randomblob(16))), 'Critical Infrastructure Threats', '("power grid" OR "water supply" OR "pipeline") AND ("attack" OR "sabotage" OR "breach")', 'infrastructure', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    (lower(hex(randomblob(16))), 'Natural Disaster Escalation', '("earthquake" OR "flood" OR "wildfire" OR "cyclone") AND ("evacuate" OR "casualties" OR "collapse")', 'natural_disaster', strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
